from __future__ import annotations

from typing import TYPE_CHECKING

from . import configs, constants, enums, events, results, types
from .configs import REQUIRED_KEYS, GaussianConfig, RunConfig
from .constants import (
    ARTIFACTS_DIR,
    CACHE_DIR,
    CACHE_ENV_VAR,
    CACHE_FILENAMES,
    COMPILE_CACHE_DIR,
    DEFAULT_PURITY_THRESHOLD,
    EVENT_DTYPE,
    GENERATORS,
    JET_DISPLAY_ORDER,
    JET_OBS,
    JET_VARIABLE_GROUPS,
    LOG2,
    LOG_RHO_FLOOR,
    METRIC_DISPLAY_SCALE,
    N_FILES,
    PANEL_COLUMNS,
    PANEL_WIDTH_INCHES,
    PANELS_PER_PAGE,
    POISON_SENTINEL,
    RUN_DIR,
    SUBSTRUCTURE_VARIABLES,
    TRUTH_SENTINEL,
    ZENODO_RECORD,
    JetVarInfo,
    artifacts_dir,
    display_order,
    figure_pages,
)
from .enums import DatasetName, LogLevel
from .events import ZXY, DatasetSplits, Events, Populations, Split
from .results import IBUResult, UnfoldingPopulations, VariableOutcome
from .types import (
    DeconvolveModel,
    DiscGradFn,
    EvalStep,
    EventArray,
    GenGradFn,
    GradsAndAux,
    KerasVariable,
    MetricRecord,
    Nested,
    StatelessOptimizer,
    TrainStep,
    Variables,
    VarInfo,
)

if TYPE_CHECKING:
    from collections.abc import Sequence
    from typing import Final

__all__: Final[Sequence[str]] = (
    "ARTIFACTS_DIR",
    "CACHE_DIR",
    "CACHE_ENV_VAR",
    "CACHE_FILENAMES",
    "COMPILE_CACHE_DIR",
    "DEFAULT_PURITY_THRESHOLD",
    "EVENT_DTYPE",
    "GENERATORS",
    "JET_DISPLAY_ORDER",
    "JET_OBS",
    "JET_VARIABLE_GROUPS",
    "LOG2",
    "LOG_RHO_FLOOR",
    "METRIC_DISPLAY_SCALE",
    "N_FILES",
    "PANELS_PER_PAGE",
    "PANEL_COLUMNS",
    "PANEL_WIDTH_INCHES",
    "POISON_SENTINEL",
    "REQUIRED_KEYS",
    "RUN_DIR",
    "SUBSTRUCTURE_VARIABLES",
    "TRUTH_SENTINEL",
    "ZENODO_RECORD",
    "ZXY",
    "DatasetName",
    "DatasetSplits",
    "DeconvolveModel",
    "DiscGradFn",
    "EvalStep",
    "EventArray",
    "Events",
    "GaussianConfig",
    "GenGradFn",
    "GradsAndAux",
    "IBUResult",
    "JetVarInfo",
    "KerasVariable",
    "LogLevel",
    "MetricRecord",
    "Nested",
    "Populations",
    "RunConfig",
    "Split",
    "StatelessOptimizer",
    "TrainStep",
    "UnfoldingPopulations",
    "VarInfo",
    "VariableOutcome",
    "Variables",
    "artifacts_dir",
    "configs",
    "constants",
    "display_order",
    "enums",
    "events",
    "figure_pages",
    "results",
    "types",
)
